### ISSUE TITLE
Adding Sampler and Zotino modules to Kasli Carrier

### ISSUE THREAD

**Issue by prasath-d** [quartiq/artiq-setup#1]
Kasli Works fine with Urukul. We would like to add Sampler and Zotino to it. 
I have added sampler to EEM2&3 and Zotino to EEM7 and Urukul DDS is already added and working in EEM4&5 ports.
I am using Artiq 4.0dev, artiq-kasli-master package with latest conda package. And I have edited the kasli.py file to add sampler and zotino entries. And I have edited device_db.py file to add those entries with channel numbers. There is no issues seen while running the program from the artiq dashboard but there isn't any outputs from the zotino or any response from the sampler. I am quite new to the artiq system. so please guide me to right docs that helps me in interfacing new extension modules.

**Comment by sbourdeauducq** [comment]
Hi,
what lab are you working at?
We need details of every file you modified etc. Also the Kasli "master" is for DRTIO, I'm not sure if this is the variant you want.

**Comment by prasath-d** [comment]
Hi, Thank you for replying.
I am working in experimental AMO lab, Freiburg(http://www.qsim.uni-freiburg.de/)
We got a pre-assembled and flashed Artiq setup with Kasli board. (https://github.com/quartiq/artiq-setup/tree/ufr-warring) with one Urukul DDS (which was connected to EEM 4&5 of Kasli) and one DIO_SMA(to EEM0 of Kasli), we are able to control them without any issues. And we wanted to interface one **Sampler (EEM0 is connected to EEM3 of Kasli)** and **one Zotino board(EEM7)** to the Kasli. 
I'm attaching two files which I modified for adding sampler and Zotino. 
[kasli_modified.zip](https://github.com/quartiq/artiq-setup/files/2116123/kasli_modified.zip)
And DRTIO Master is the variant we want. but we are not going to control additional DRTIO satellite.
(A Standalone variant that controls all extension modules with an ethernet installed from SF0 Cage).
Thank you

**Comment by prasath-d** [comment]
Hi, 
Do I have to reflash the kasli for interfacing new modules?
if not, What other files I have to edit to get Zotino and Sampler interfaced?
Thank you

**Comment by jordens** [comment]
Yes. You should edit your target variant definition, build everything, flash everything, and update your device_db. Alternatively: your current EEM setup is compatible with the `ptb` variant in artiq master. And it will be if you use the corresponding EEM slots for Sampler and Zotino. You can build and use that variant.

**Comment by prasath-d** [comment]
can I flash the kasli with **tester** variant and rewire the extensions as given in the tester example?
Thanks

**Comment by jordens** [comment]
Sure, it's just more rewiring.

**Comment by prasath-d** [comment]
I am missing some key procedure.
1. Rewired the Extension modules according to **Tester** variant.
2. updated the device_db.py file
3. flashed tester variant:` **artiq_flash -t kasli -V tester -f flash_storage.img storage start** `
Output:
```
Open On-Chip Debugger 0.10.0-00013-gbb7beda (2018-02-13-15:56)
Licensed under GNU GPL v2
For bug reports, read
	http://openocd.org/doc/doxygen/bugs.html
none separate
adapter speed: 25000 kHz
Info : ftdi: if you experience problems at higher adapter clocks, try the command "ftdi_tdo_sample_edge falling"
Info : clock speed 25000 kHz
Info : JTAG tap: xc7.tap tap/device found: 0x13631093 (mfg: 0x049 (Xilinx), part: 0x3631, ver: 0x1)
Info : gdb server disabled
TEMP 57.57 C
VCCINT 0.995 V
VCCAUX 1.777 V
VCCBRAM 0.998 V
VPVN 0.000 V
VREFP 0.000 V
VREFN 0.000 V
VCCPINT 0.000 V
VCCPAUX 0.000 V
VCCODDR 0.000 V
loaded file /home/prasath/anaconda3/envs/artiq-test/share/bscan-spi-bitstreams/bscan_spi_xc7a100t.bit to pld device 0 in 0s 231542us
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
flash 'jtagspi' found at 0x00000000
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
Info : sector 68 took 129 ms
erased sectors 68 through 68 on flash bank 1 in 0.128898s
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
wrote 47 bytes from file flash_storage.img to flash bank 1 at offset 0x00440000 in 0.001817s (25.261 KiB/s)
Info : Found flash device 'sp s25fl128' (ID 0x00182001)
read 47 bytes from file flash_storage.img and flash bank 1 at offset 0x00440000 in 0.000279s (164.511 KiB/s)
contents match
```
flashing looks ok to me. but the extension modules sampler and zotino doesn't work yet. And DIO_SMA and Urukul works in the Previous EEM locations (EEM0 and EEM5&4 according to master variant.
I don't know what I am missing here.

**Comment by jordens** [comment]
You are only flashing the `storage` part of the flash. That's just mac and ip configuration. As I explained, you'll have to build the tester bitstream, runtime, and bios.

**Comment by prasath-d** [comment]
Worked!!! Thanks a lot for helping me in setting Kasli up.
